language: scala
scala:
- 2.13.1
jdk:
- openjdk8
node_js:
- node
env:
  global:
  - secure: G22xc2tleUWSdD3ucDUYffK1r050V5THD4kzpflkRutRUjlZB4lT3FUkvGB72+jhdCWkbhdIeCZRLFRuuJNsg8MlNTUd5aIK8QPM9NYGv0QULK0aWLKep1iXwBtExXEShTblI8w6UD7ZxT7thlmvUQjHYB5fv2kGqdXm7XxFQc33YbD05+s4byJSoZoPtnzrVmC6o5J08crcoLHsz0j6EvX9C/wHHawUbKpDglzzhAVJyByb5Oy1JKaIwT3adfvZ/xckqzS4/qJVVSE2WUU0rHY+N0Mi/FYmMDP2iT6AdatN0Ss/3mfPIwWtgyhcBamVT8RGqp+xUNwmt9wttW6EbdDAOETQK03XMuuTN4yqxQWBxNP0G40strNsBkPVaH5rIN0rtsbz5pHv4j15STQGnS9AemSeX7SO/dDLf6mb+RYStXXGNsAW5/2yjwy3oTU97LIDGYtJQ63GSgzRNWqSQaniHSa+GODlbjqJDGFx9gRaUDBqNXyetgz7VzoElTjnzLY25oJhAh1t9GgphEaAAPDC4GGfcK9uwFqnyhEfP+W77mEmCBGGsolcgpRGnP28WlB7Yn3k55DTUAnFhxFQK2fEbv/ZuLR/NNkX9Oe44G2twJF1XCO2bq/6Z5VFyFh1ezQSaIzF474mSLgpvKJQENDYA9ky2lOatBSCq4Y+5Cg=
script:
- sbt test
