language: scala
scala:
  - 2.13.1
jdk:
  - openjdk8
node_js:
  - node
env:
  - secure: "eAypY+1pB4OSXx3S8QP+iOgordwMcQwpAD4cpp3VtNc6alvKcvRKtj1RZv8uyVc0LCmyzCSngFzXnkkhYOPbMo+heZZ7Uo0oCDQOEkLdct0VuZr9LoBr17A/zVXgW0Wwq6VIliPyKl+0dFyLUj5e/RYwZqTpoMn7ZYEEP1TgyUG2sWoyPfOtXS9XraMqz832HvpcYw17G/+IOytMPqIrPPu7jshwzuIVnLm+hZC7MDv5Hq3Xog6bav40NyEZTBsrBlRduQUcpP7dHDp2cHwtEysfj3zfhd7s0ivEy5rQsRNc/FLD1TPDRBOwnQSWMk2GduOXnsoTEGX3Nqrw6jQB9+p763J4i0gpz3szRWdDy6eKgEVt3MfjV2DfHQo6UnBNYRXYIANd1iBJkt8vcvpkv6RsKzV1anbaTq/m/sWAzp0j/8J1H/5EZt93nu0PW9yezrtGxrJmYkYeZUk43bwB7ojv95vOv2uzYXtS0HvJMpcQFzIoxiJfSiKsqHp0O/ldkOSe8A8CV4drnzrkZXF/Vs9ghEVQD/mTcq0CnMLds2DLJmS2Jxq/kU7DMAS5VLzULO33PlEHPaTnqx2T8i3AvSUAkZQ/X0wplN0MKK2tl2jEO4OH1wbU0AcEL9P5vJ6TDQOgzgK8Q3AY4zJYr/D6/NbF0Cd4R38PCiuqg24Hs3Q="
script:
  - sbt saxonJVM/test
